spring.application.name=spring
spring.web.resources.static-locations=classpath:/static/

# Maria DB Settings
spring.datasource.url=jdbc:mariadb://mariadb:3306/mariadb
spring.datasource.username=mariadb
spring.datasource.password=mariadb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true;
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.change-log=classpath:/db/migrations/changelog.xml

# Server Configuration
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true
server.port=8080

# Logging
spring.jpa.properties.hibernate.show_sql=false
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.sintraqos.portfolioproject=DEBUG

# custom-settings
settings.logSettings=false

# User
settings.usernameMinLength=2
settings.usernameMaxLength=200
settings.passwordMinLength=2
settings.passwordMaxLength=200
settings.passwordContainCapital=true
settings.passwordContainSpecialChar=false

# Forum
settings.messageMinLength=2
settings.messageMaxLength=8192
#settings.messageCooldown=0.5
settings.messageCooldown=5

# Schedule
settings.retrieveGameTime=0 0 12 * * *
# Run every five seconds, use the above stated cron for running every day at 12:00
#settings.retrieveGameTime=*/5 * * * * *

# API
settings.apiURL=http://localhost:8081

# Game Review
settings.gameReviewScore=8